from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1610, 900)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(212, 237, 255);\n"
"color: rgb(25, 68, 124);")
        self.photo_label = QtWidgets.QLabel(Form)
        self.photo_label.setGeometry(QtCore.QRect(1060, 140, 350, 350))
        self.photo_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.photo_label.setText("")
        self.photo_label.setObjectName("photo_label")
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(60, 20, 1511, 91))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(24)
        self.title_label.setFont(font)
        self.title_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.previous_pushButton = QtWidgets.QPushButton(Form)
        self.previous_pushButton.setGeometry(QtCore.QRect(20, 852, 75, 41))
        self.previous_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_pushButton.setIcon(icon)
        self.previous_pushButton.setIconSize(QtCore.QSize(100, 80))
        self.previous_pushButton.setFlat(True)
        self.previous_pushButton.setObjectName("previous_pushButton")
        self.next_pushButton = QtWidgets.QPushButton(Form)
        self.next_pushButton.setGeometry(QtCore.QRect(1510, 852, 75, 41))
        self.next_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_pushButton.setIcon(icon1)
        self.next_pushButton.setIconSize(QtCore.QSize(100, 80))
        self.next_pushButton.setFlat(True)
        self.next_pushButton.setObjectName("next_pushButton")
        self.category_label = QtWidgets.QLabel(Form)
        self.category_label.setGeometry(QtCore.QRect(140, 120, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.category_label.setFont(font)
        self.category_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.category_label.setText("")
        self.category_label.setObjectName("category_label")
        self.cuisine_label = QtWidgets.QLabel(Form)
        self.cuisine_label.setGeometry(QtCore.QRect(510, 120, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.cuisine_label.setFont(font)
        self.cuisine_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cuisine_label.setText("")
        self.cuisine_label.setObjectName("cuisine_label")
        self.categories_label = QtWidgets.QLabel(Form)
        self.categories_label.setGeometry(QtCore.QRect(40, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.categories_label.setFont(font)
        self.categories_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.categories_label.setObjectName("categories_label")
        self.categories_label_2 = QtWidgets.QLabel(Form)
        self.categories_label_2.setGeometry(QtCore.QRect(410, 120, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.categories_label_2.setFont(font)
        self.categories_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.categories_label_2.setObjectName("categories_label_2")
        self.ingredients_label = QtWidgets.QLabel(Form)
        self.ingredients_label.setGeometry(QtCore.QRect(40, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ingredients_label.setFont(font)
        self.ingredients_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ingredients_label.setObjectName("ingredients_label")
        self.instructions_label_2 = QtWidgets.QLabel(Form)
        self.instructions_label_2.setGeometry(QtCore.QRect(40, 480, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.instructions_label_2.setFont(font)
        self.instructions_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.instructions_label_2.setObjectName("instructions_label_2")
        self.ingredients = QtWidgets.QListWidget(Form)
        self.ingredients.setEnabled(True)
        self.ingredients.setGeometry(QtCore.QRect(40, 200, 481, 261))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ingredients.setFont(font)
        self.ingredients.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.477, x2:1, y2:0.511, stop:0 rgb(239, 250, 255), stop:1 rgb(243, 247, 255));\n"
"border: 1px solid rgb(69, 111, 179);\n"
"border-radius: 5px;")
        self.ingredients.setFrameShape(QtWidgets.QFrame.Box)
        self.ingredients.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ingredients.setLineWidth(1)
        self.ingredients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ingredients.setProperty("showDropIndicator", False)
        self.ingredients.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.ingredients.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.ingredients.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ingredients.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ingredients.setObjectName("ingredients")
        self.instructions = QtWidgets.QTextBrowser(Form)
        self.instructions.setGeometry(QtCore.QRect(40, 510, 1511, 331))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.instructions.setFont(font)
        self.instructions.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.477, x2:1, y2:0.511, stop:0 rgb(239, 250, 255), stop:1 rgb(243, 247, 255));\n"
"border: 1px solid rgb(69, 111, 179);\n"
"border-radius: 5px;")
        self.instructions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.instructions.setObjectName("instructions")
        self.fav_button = QtWidgets.QPushButton(Form)
        self.fav_button.setGeometry(QtCore.QRect(10, 45, 41, 41))
        self.fav_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fav_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("notfav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fav_button.setIcon(icon2)
        self.fav_button.setIconSize(QtCore.QSize(40, 40))
        self.fav_button.setCheckable(False)
        self.fav_button.setFlat(True)
        self.fav_button.setObjectName("fav_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "recipe"))
        self.previous_pushButton.setShortcut(_translate("Form", "Left"))
        self.next_pushButton.setShortcut(_translate("Form", "Right"))
        self.categories_label.setText(_translate("Form", "Category:"))
        self.categories_label_2.setText(_translate("Form", "Cuisine:"))
        self.ingredients_label.setText(_translate("Form", "Ingredients:"))
        self.instructions_label_2.setText(_translate("Form", "Instructions:"))

